### ISSUE TITLE
Set p.detected in populate.py

### ISSUE THREAD

**Issue by mtlam** [devanshkv/PsrPopPy2#1]
When calling populate.generate() with a survey, it returns all of the pulsars in the simulation but all of the p.detected flags are False. Around line 418 of populate.py, I think this is solved by just adding a p.detected=True but this should be checked, especially in relation to multiple surveys in surveyList (but I still think it's okay).

**Comment by devanshkv** [comment]
It is designed in this way so that later when you run dosurvey, you can distinguish between detected vs. discovered pulsars in a particular survey. Setting p.detected=True in populate.generate() will lead to an incorrect number of discoveries while running dosurvey.

**Comment by mtlam** [comment]
I think this is problematic though as it means you must run dosurvey but cannot simply run populate.generate() with a survey. It seems like somehow the code should accommodate both. Right now if I run populate.generate() with a survey, I have no way of knowing which 100 pulsars were actually detected, unless there's something else I'm missing.
